# Generated by Django 5.1.2 on 2024-11-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonebook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="job",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
